"""memex views — regenerate machine-owned navigation catalogs (.memex/views/).

These are NOT wiki pages: no YAML frontmatter, no `kind: hub`, excluded from
the canonical graph (canon.py only recalls wiki/{topics,entities,decisions}).
They are regenerated from index.json on every synthesis, so the whole
.memex/views/ tree can be cleared wholesale without touching user knowledge.

Layout produced:
  .memex/views/brain-index.md        — catalog of every wiki page, by section.
  .memex/views/projects-index.md     — index of the per-project hub pages.
  .memex/views/projects/<project>.md — one hub per project/initiative.

Projects are semantic (initiative/area/repo) — many workspaces can feed one
project, and one generic workspace can feed many projects.
"""

from __future__ import annotations

from collections import defaultdict
from pathlib import Path


def write_views(vault: Path, index: dict) -> None:
    """Regenerate .memex/views/brain-index.md + project hubs from the index."""
    vault = Path(vault)
    views_dir = vault / ".memex" / "views"
    views_dir.mkdir(parents=True, exist_ok=True)
    _write_brain_index(views_dir, index)
    _write_project_hubs(views_dir, index)


def _write_brain_index(views_dir: Path, index: dict) -> None:
    """The brain catalog: one line per page, grouped by wiki section."""
    sections = {"topics": [], "entities": [], "decisions": []}
    for p in index.get("pages", []):
        sections.setdefault(p.get("section", "topics"), []).append(p)
    lines = ["# Brain index", "", "Navigable catalog of wiki pages.", ""]
    for sec, title in [("topics", "Topics"), ("entities", "Entities"),
                       ("decisions", "Decisions")]:
        lines.append(f"## {title}")
        for p in sorted(sections.get(sec, []), key=lambda x: x["slug"]):
            lines.append(f"- [[{p['slug']}]] — {p.get('summary', '')}")
        lines.append("")
    (views_dir / "brain-index.md").write_text("\n".join(lines), encoding="utf-8")


def _write_project_hubs(views_dir: Path, index: dict) -> None:
    """Per-project hub pages. One page per project/initiative that links its
    architecture + sessions + docs. LLM-free, regenerated from the index each
    time. The .memex/views/projects/ directory is machine-owned, so stale
    generated *.md files are cleared before regenerating (a project that lost
    all its pages disappears on its own)."""
    by_proj = defaultdict(list)
    for p in index.get("pages", []):
        if p.get("project"):
            by_proj[p["project"]].append(p)

    hubs_dir = views_dir / "projects"
    hubs_dir.mkdir(parents=True, exist_ok=True)
    for stale in hubs_dir.glob("*.md"):
        try:
            stale.unlink()
        except OSError:
            pass

    if not by_proj:
        return

    def _kind(p):
        srcs = [str(s) for s in (p.get("sources") or [])]
        if any(s.startswith("analyze:") for s in srcs):
            return "arch"
        if any(s.startswith("doc:") for s in srcs):
            return "doc"
        return "session"

    for proj, plist in sorted(by_proj.items()):
        buckets = {"arch": [], "session": [], "doc": []}
        for p in plist:
            buckets[_kind(p)].append(p)
        lines = [f"# {proj}", "",
                 f"*Project hub — {len(plist)} page(s), auto-generated by memex.*", ""]
        for key, label, emoji in [("arch", "Arquitetura", "🏛️"),
                                  ("session", "Sessões", "💬"),
                                  ("doc", "Docs", "📄")]:
            bucket = sorted(buckets[key], key=lambda x: x["slug"])
            if not bucket:
                continue
            lines.append(f"## {emoji} {label}")
            for p in bucket:
                lines.append(f"- [[{p['slug']}]] — {p.get('summary') or ''}")
            lines.append("")
        (hubs_dir / f"{proj}.md").write_text("\n".join(lines).rstrip() + "\n",
                                             encoding="utf-8")

    idx_lines = ["# Projects", "",
                 "One hub per project/initiative — each ties together "
                 "sessions · docs · architecture.", ""]
    for proj in sorted(by_proj):
        idx_lines.append(f"- [[{proj}]] ({len(by_proj[proj])})")
    (views_dir / "projects-index.md").write_text("\n".join(idx_lines) + "\n",
                                                 encoding="utf-8")
